import Head from "next/head";
import Link from "next/link";

export default function Home() {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href={"/"}>
                <span>Home</span>
            </Link>
            {/* <Link href={"/about"}>
                <span> About</span>
            </Link>
            <Link href={"/blog"}>
                <span> Blog</span>
            </Link> */}
        </>
    );
}
